import type { Lead } from "@/models/lead/lead";

export const leadRecords: Lead[] = [
  {
    id: "ld-1001",
    leadId: "LD-1001",
    leadName: "Aarav Mehta",
    companyName: "BlueOrbit",
    email: "aarav.mehta@blueorbit.io",
    phone: "+91 98450 11001",
    leadSource: "Website",
    status: "New",
    leadScore: 71,
    assignedTo: "Priya Sharma",
    createdDate: "2026-08-02",
    industry: "Technology",
    projectType: "Implementation",
    website: "https://blueorbit.io",
    companySize: "201-500",
    annualRevenue: "$10M-$50M",
    address: "Koramangala, Bengaluru",
    subsidiary: "i-ERP India",
  },
  {
    id: "ld-1002",
    leadId: "LD-1002",
    leadName: "Mia Rodriguez",
    companyName: "NorthWind",
    email: "mia.r@northwind.co",
    phone: "+1 415 882 4402",
    leadSource: "Referral",
    status: "Qualified",
    leadScore: 88,
    assignedTo: "Liam Walker",
    createdDate: "2026-08-03",
    industry: "Logistics",
    projectType: "Expansion",
    website: "https://northwind.co",
    companySize: "501-1000",
    annualRevenue: "$50M-$100M",
    address: "San Francisco, CA",
    subsidiary: "i-ERP US",
  },
  {
    id: "ld-1003",
    leadId: "LD-1003",
    leadName: "Noah Bennett",
    companyName: "Apex Retail",
    email: "noah.b@apexretail.com",
    phone: "+44 20 7946 1003",
    leadSource: "LinkedIn",
    status: "Contacted",
    leadScore: 62,
    assignedTo: "Arjun Rao",
    createdDate: "2026-08-04",
    industry: "Retail",
    projectType: "Upgrade",
    website: "https://apexretail.com",
    companySize: "51-200",
    annualRevenue: "$5M-$10M",
    address: "London, UK",
    subsidiary: "i-ERP Europe",
  },
  {
    id: "ld-1004",
    leadId: "LD-1004",
    leadName: "Zara Khan",
    companyName: "GreenField",
    email: "zara.khan@greenfield.ae",
    phone: "+971 50 441 1004",
    leadSource: "Campaign",
    status: "Qualified",
    leadScore: 91,
    assignedTo: "Priya Sharma",
    createdDate: "2026-08-05",
    industry: "Energy",
    projectType: "Greenfield",
    website: "https://greenfield.ae",
    companySize: "1000+",
    annualRevenue: "$100M+",
    address: "Dubai, UAE",
    subsidiary: "i-ERP MEA",
  },
  {
    id: "ld-1005",
    leadId: "LD-1005",
    leadName: "Ethan Cole",
    companyName: "Vertex Marine",
    email: "ethan.cole@vertexmarine.com",
    phone: "+1 713 555 1005",
    leadSource: "Partner",
    status: "Disqualified",
    leadScore: 34,
    assignedTo: "Liam Walker",
    createdDate: "2026-08-06",
    industry: "Marine",
    projectType: "Assessment",
    website: "https://vertexmarine.com",
    companySize: "11-50",
    annualRevenue: "$1M-$5M",
    address: "Houston, TX",
    subsidiary: "i-ERP US",
  },
  {
    id: "ld-1006",
    leadId: "LD-1006",
    leadName: "Ananya Iyer",
    companyName: "Skyline Infra",
    email: "ananya.iyer@skylineinfra.in",
    phone: "+91 98840 11006",
    leadSource: "Website",
    status: "Contacted",
    leadScore: 54,
    assignedTo: "Arjun Rao",
    createdDate: "2026-08-07",
    industry: "Construction",
    projectType: "Implementation",
    website: "https://skylineinfra.in",
    companySize: "201-500",
    annualRevenue: "$10M-$50M",
    address: "Chennai, India",
    subsidiary: "i-ERP India",
  },
  {
    id: "ld-1007",
    leadId: "LD-1007",
    leadName: "Sarah Chen",
    companyName: "TechVision Inc",
    email: "sarah.chen@techvision.io",
    phone: "+1 206 555 1007",
    leadSource: "LinkedIn",
    status: "Qualified",
    leadScore: 88,
    assignedTo: "Priya Sharma",
    createdDate: "2026-08-08",
    industry: "Technology",
    projectType: "Implementation",
    website: "https://techvision.io",
    companySize: "201-500",
    annualRevenue: "$10M-$50M",
    address: "Seattle, WA",
    subsidiary: "i-ERP US",
  },
  {
    id: "ld-1008",
    leadId: "LD-1008",
    leadName: "Marcus Webb",
    companyName: "Apex Logistics",
    email: "marcus.webb@apexlog.com",
    phone: "+44 161 555 1008",
    leadSource: "Website",
    status: "Contacted",
    leadScore: 62,
    assignedTo: "Liam Walker",
    createdDate: "2026-08-09",
    industry: "Logistics",
    projectType: "Expansion",
    website: "https://apexlog.com",
    companySize: "51-200",
    annualRevenue: "$5M-$10M",
    address: "Manchester, UK",
    subsidiary: "i-ERP Europe",
  },
  {
    id: "ld-1009",
    leadId: "LD-1009",
    leadName: "Aisha Rahman",
    companyName: "Global Textile Group",
    email: "aisha.r@gtg.pk",
    phone: "+92 21 555 1009",
    leadSource: "Referral",
    status: "New",
    leadScore: 45,
    assignedTo: "Arjun Rao",
    createdDate: "2026-08-10",
    industry: "Manufacturing",
    projectType: "Assessment",
    website: "https://gtg.pk",
    companySize: "501-1000",
    annualRevenue: "$50M-$100M",
    address: "Karachi, Pakistan",
    subsidiary: "i-ERP MEA",
  },
  {
    id: "ld-1010",
    leadId: "LD-1010",
    leadName: "Daniel Okonkwo",
    companyName: "Harbor Steel",
    email: "daniel.o@harborsteel.com",
    phone: "+234 802 555 1010",
    leadSource: "Campaign",
    status: "Disqualified",
    leadScore: 38,
    assignedTo: "Priya Sharma",
    createdDate: "2026-08-11",
    industry: "Manufacturing",
    projectType: "Upgrade",
    website: "https://harborsteel.com",
    companySize: "201-500",
    annualRevenue: "$10M-$50M",
    address: "Lagos, Nigeria",
    subsidiary: "i-ERP MEA",
  },
];
