import type { ScreenMetadata } from "@/models/metadata/metadata";

/**
 * Customer Master is a Hybrid screen in the process-flow document.
 * This mock proves GenericPage can render metadata + merged custom fields.
 */
export const customerMasterMetadata: ScreenMetadata = {
  screen: {
    code: "customer-master",
    name: "Customer Master",
    route: "/masters/customers",
    renderMode: "hybrid",
    entityName: "customer-master",
    apiBasePath: "/api/v1/customers",
    workflowEnabled: false,
    printEnabled: false,
    aiEnabled: true,
  },
  layout: { mode: "form", columns: 12 },
  sections: [
    {
      code: "main",
      title: "Customer Details",
      description: "Core identity fields used across sales and finance.",
      type: "header",
      fields: [
        {
          fieldKey: "customerCode",
          label: "Customer Code",
          dataType: "text",
          controlType: "text",
          required: true,
          readOnly: false,
          visible: true,
          width: 4,
          displayOrder: 1,
          isCustom: false,
        },
        {
          fieldKey: "customerName",
          label: "Customer Name",
          dataType: "text",
          controlType: "text",
          required: true,
          readOnly: false,
          visible: true,
          width: 4,
          displayOrder: 2,
          isCustom: false,
        },
        {
          fieldKey: "email",
          label: "Email",
          dataType: "text",
          controlType: "text",
          required: true,
          readOnly: false,
          visible: true,
          width: 4,
          displayOrder: 3,
          isCustom: false,
        },
        {
          fieldKey: "creditLimit",
          label: "Credit Limit",
          dataType: "number",
          controlType: "number",
          required: false,
          readOnly: false,
          visible: true,
          width: 4,
          displayOrder: 4,
          isCustom: false,
        },
        {
          fieldKey: "status",
          label: "Status",
          dataType: "text",
          controlType: "select",
          required: true,
          readOnly: false,
          visible: true,
          width: 4,
          displayOrder: 5,
          isCustom: false,
          options: [
            { value: "Active", label: "Active" },
            { value: "Inactive", label: "Inactive" },
          ],
        },
        {
          fieldKey: "project_code",
          label: "Project Code",
          dataType: "text",
          controlType: "text",
          required: false,
          readOnly: false,
          visible: true,
          width: 4,
          displayOrder: 10,
          isCustom: true,
        },
      ],
    },
  ],
  actions: [
    {
      actionKey: "save",
      label: "Save",
      actionType: "api",
      endpoint: "/api/v1/customers",
      method: "POST",
      variant: "contained",
    },
  ],
};
